meta_product_name: "Pillami"
meta_title: "Pillami - Votre assistant santé au quotidien"
meta_description: "Gérez vos médicaments, recevez des rappels de prise et suivez vos sensations au quotidien. Simple, accessible et sécurisé."
meta_image: "https://res.cloudinary.com/dpyoe1s3a/image/upload/v1765381154/facebook_arb0uo.png"
